tosca_definitions_version: cloudify_dsl_1_3

plugins:
  my_workflow_plugin:
    executor: central_deployment_agent
    source: https://github.com/NiltonDuarte/CloudifyWorkflow/archive/master.zip
    package_name: my_workflow
    package_version: '0.0'

workflows:
  my_workflow: 
    mapping: my_workflow_plugin.my_workflow.my_workflow_method
    parameters:
      param:
        description: this parameter is mandatory